# Site settings
title: Code Island
email: info@code-island.org
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://code-island.org" # the base hostname & protocol for your site
port: 4001
# permalink: article/:title
